print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')

print ('This is an additional line I added in this program.')
#print("This line does not appear on the screen and # denotes the start of a comment.")